### ISSUE TITLE
SPWebPartErrorCode.ScriptLoadError when adding web

### ISSUE THREAD

**Issue by shurick81** [SharePoint/sp-dev-fx-webparts#101]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When I add a web part on the page, I expect it to show content

#### Observed Behavior
When adding web part on the page I am asked whether to leave the page or stay.
If I choose leave, I am transferred to the empty modern page again, no web parts.
If I choose stay, I can see the web part with following error.
[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.undefined.d7892b04-4654-4dc2-94dc-3a3cd7bb3416,Error: ***Failed to load component "90a04bb9-fbdf-43d1-bfe1-0491d34941be" (undefined). Original error: script resources due to: undefined. CALLSTACK:: Error at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-loader_en-us_4ec28636b0f9b465bd02537852aebf16.js:57:16567) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-webpart-base_en-us_8d0a284d4d0d8e404879f4b5fcc7cc99.js:47:22094) at t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-webpart-base_en-us_8d0a284d4d0d8e404879f4b5fcc7cc99.js:47:22502) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.005/sp-webpart-base_en-us_8d0a284d4d0d8e404879f4b5fcc7cc99.js:48:604)

#### Steps to Reproduce
1. clone repository
2. copy the "react-officegraph" folder to project directory
3. run nodejs cmd and select project directory via cd
4. npm i
5. gulp serve --nobrowser
6. gulp package-solution
7. upload \sharepoint\react-officegraph.spapp to app catalog in dev o365 tenant
8. add app on the site, for example, on /site/dev
9. add new modern page, add web part "Trending in the sites I"

**Comment by shurick81** [comment]
My bad, the error was in case if I added the web part on the page when the gulp serve was already terminated. This issue is to be closed I guess.

**Comment by Padmapriyashree** [comment]
I face the same issue still with the Officegraph web part.
The aspx page created as directed in Readme page returns nothing and after adding  app on the site,
add new modern page, add web part "Trending in the sites I"
I get the below in the added webpart.

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.undefined.83f0e319-95a2-4cff-84ca-d50d693e92ee,Error: ***Failed to load component "90a04bb9-fbdf-43d1-bfe1-0491d34941be" (undefined). Original error: ***Failed to load entry point from component "90a04bb9-fbdf-43d1-bfe1-0491d34941be" (undefined). script resources due to: {1}. CALLSTACK:: Error at t.prototype._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:25072) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:24062) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:25406) at t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:25848) at e.prototype._handleModulePromiseRejection (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:55681) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:46096) at k (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:2381) at L (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:2469) at A (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:2291) at D (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:1887)
