### ISSUE TITLE
React Birthday not showing any result

### ISSUE THREAD

**Issue by komzy96** [SharePoint/sp-dev-fx-webparts#1030]
Hey can any one help ive been trying to use the react-birthday webpart but im getting this issues attached
![Screenshot (156)](https://user-images.githubusercontent.com/48515129/66834195-19770580-ef55-11e9-83b3-076d84484732.png)

**Comment by hugoabernier** [comment]
Hey @komzy96 did you ever resolve this issue?

I'll mark the issue as closed since there hasn't been any activity for a while. If you're still experiencing issues, feel free to open a new one. I encourage you to follow the issue template, as it helps making it easier for other community members to solve issues.
