### ISSUE TITLE
AngularJS Greetings not working

### ISSUE THREAD

**Issue by sheiknaveed** [SharePoint/sp-dev-fx-webparts#1248]
Dear Team,
I am using this webpart in Sharepoint Online and it do not show the logged in user name and photo

**Comment by hugoabernier** [comment]
@sheiknaveed we'll need more information in order to route your issue to the right people.

Can you re-submit this issue, but make sure to fill the issue template so that we can get in touch with the right people who can help you.

I know it takes a bit more time for you, but it can make the difference between your issue remaining opened forever and getting you answers.

Thanks for your understanding.
