### ISSUE TITLE
AngularJS Greetings not taking values from logged user

### ISSUE THREAD

**Issue by sheiknaveed** [SharePoint/sp-dev-fx-webparts#1249]
Dear Team,
I am using the webpart "AngularJS Greetings" in Sharepoint Online and it do not show the logged in user name and photo.
I am able to crate an spkkg package. When I add the webpart in Sharepoint Online it do not take the information on the logged in user.
<img width="354" alt="greeting" src="https://user-images.githubusercontent.com/60134901/80314125-9b978f00-8800-11ea-9728-f9b032afbf7f.PNG">

**Comment by hugoabernier** [comment]
@sheiknaveed we'll need more information in order to route your issue to the right people.

Can you re-submit this issue, but make sure to fill the issue template so that we can get in touch with the right people who can help you.

I know it takes a bit more time for you, but it can make the difference between your issue remaining opened forever and getting you answers.

If you have any questions about how to create issues, please follow the [contribution guidelines](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/.github/CONTRIBUTING.md)

Thanks for your understanding.

**Comment by sheiknaveed** [comment]
Dear Hugo,
I had provide the information. I am not sure what more information do you required.
Thank you


Sheik Naveed
شيك نافيد
Academic Systems Administrator
مسؤول النظم الأكاديمية
Smart Servicesالخدمات الذكية
Tel: 800- MBRU (6278)
Direct +9714 383 8606
Naveed.Sheik@mbru.ac.ae
www.mbru.ac.ae
P.O. Box 505055, Dubai,  UAE

**Comment by hugoabernier** [comment]
@sheiknaveed you may want to watch this video which explains how to file an issue:
https://www.youtube.com/watch?v=9nEP8pJ2LRw

As you can imagine, we get tons of issue requests and this repository is maintained by people who volunteer their time. Authors of the samples don't automatically get notified when issues get created unless you fill the template as provided.

The guidance is provided within the issue template as follows:
> _This is an example of guidance_
> 
> _DELETE THIS PARAGRAPH AFTER READING

We want to make sure you get the help you deserve!

Thank you for your understanding.
