### ISSUE TITLE
New sample web parts

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-fx-webparts#176]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#spfx-webparts
Hi guys,

Sorry is this is not the correct place to ask this question (I've read the guidelines, but still not sure...)
What is the best approach to suggest new web part samples for the gallery? 
Should I just create the sample if I can't find a related one in the gallery and submit it as a PR, or should I first submit the idea for your approval in case it doesn't go in line with what you would like to publish?

Thanks
Joel

**Comment by ferrx** [comment]
@joelfmrodrigues Good question, I'm wondering this as well. It does sound like based on their Contributors section on the root Readme that client-side PRs are welcome. I interpret this as saying "you can PR a new sample for something like a custom web part, but you can't PR something like a change to the Gulp tasks or other internal components of SPFx"...

> We welcome your input on issues and suggestions for new samples. We do also welcome community contributions around the client-side web parts.

**Comment by VelinGeorgiev** [comment]
My approach with new samples or bug fixes is to do a pull request to the dev branch.
Then we discuss in the pull request feed if anything else is required. It works for me , the Microsoft and the non-Microsoft guys as well since everyone is busy anyway. This is a direct way to communicate within the current pull request for the current code base. If the sample does not fit the repo, the pull request will simply  be rejected.

**Comment by VesaJuvonen** [comment]
Closing as answered. Thanks Joel also for submitting plenty of contributions since. PRs are more than welcome for the samples in this repository.
