### ISSUE TITLE
angular-msgraph sample - unable to bundle --ship: issue with HelloJS and UglifyJS

### ISSUE THREAD

**Issue by luismanez** [SharePoint/sp-dev-fx-webparts#220]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
You can run "gulp bundle --ship" without any issue

#### Observed Behavior
When running "gulp bundle --ship" with latest spfx version, you get a weird issue from Webpack and UglifyJS:

"
Error - [webpack] 'dist':
ms-graph.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (hello) [./~/source-map-loader!./lib/webparts/msGraph/app/aad.js:1,0]
"
![image](https://cloud.githubusercontent.com/assets/9392197/26322205/2a6a2f08-3f2a-11e7-8686-6cd7b8338bd6.png)

#### Steps to Reproduce
Clone project and follow install instructions, then run "gulp bundle --ship" (without the --ship argument the bundle task works).

Thanks for your help.

**Comment by waldekmastykarz** [comment]
The problem seems to be with the use of the `let` keyword (https://github.com/SharePoint/sp-dev-fx-webparts/blob/dbd7d66ff60ed18bca4f3754447bfe089dd3d9d1/samples/angular-msgraph/src/webparts/msGraph/app/aad.js#L1) which isn't a part of the ES5 standard and isn't supported by UglifyJS. In TS files, `let` is replaced `var` in the transpilation process. As the adal.js file has the .js extension, it isn't processed by TypeScript and `let` is passed as-is to UglifyJS which causes it to break. To fix the error, you should replace `let` with `var`.

**Comment by Danny-Engelman** [comment]
>  To fix the error, you should replace let with var.

Can adal.js be renamed to adal.ts ? So TypeScript does the job?  (yes I am lazy)

**Comment by waldekmastykarz** [comment]
Yes, you could do that too.

**Comment by luismanez** [comment]
ouch! shame on me! didn't figure that out. yeah, I just renamed the file to .ts, and bundle --ship works as expected. Thanks for you help @waldekmastykarz !

**Comment by waldekmastykarz** [comment]
You're welcome @luismanez
