### ISSUE TITLE
[Question] Warning! message from SharePoint framework

### ISSUE THREAD

**Issue by honb** [SharePoint/sp-dev-fx-webparts#235]
Hi all, 

Yesterday I saw a warning message from HelloWorld web part which I haven't seen before.
![image](https://user-images.githubusercontent.com/26110193/26972983-55e4e7aa-4d3e-11e7-8d3e-5bb8d4021a9d.png)

It shown both in workbench.aspx & sharepoint page which installed web part.
I'm using Azure CDN to store resource files and I think the same problem with Office 365 CDN (difference domain with SharePoint site url)
Is there any update from framework?

Learn more here: https://technet.microsoft.com/en-us/library/bb794823.aspx

**Comment by iclanton** [comment]
See [this thread](https://github.com/SharePoint/sp-dev-docs/issues/634).

As @patmill mentioned, the warning message is intentional, and shouldn't block anything. It's to stop social engineering type attacks on people. This is to prevent users from becoming victims of [Self-XSS attacks](https://en.wikipedia.org/wiki/Self-XSS)

**Comment by nikunj231991** [comment]
In workbench i get this error but why i get after deploying to azure cdn?
I already done "gulp trust-dev-cert and set the https property to true in the serve.json file."
but still getting

Warning!
Use of this tool exposes you to potential security threats which can result in others gaining access to your personal Office 365 data (documents, emails, conversations and more). Make sure you trust the person or organization that asked you to access this tool before proceeding.

Learn more here: https://technet.microsoft.com/en-us/library/bb794823.aspx
