### ISSUE TITLE
Cannot set headers for httpClient request

### ISSUE THREAD

**Issue by honb** [SharePoint/sp-dev-fx-webparts#240]
I'm trying to send a request to an external API by using httpClient which include Authorization in request headers.
But the Authorization header always gone and I could not see it. I have checked with many options:
1) `httpClient.get('https://test.net/api/', {
        headers: {
          'Accept': 'application/json',
          'Authorization': 'Bearer ' + accessToken
        }
      })`
2) `
const opt: ISPHttpClientOptions = { headers: { 'Authorization': 'Bearer ' + accessToken } };
 spHttpClient/httpClient.get('https://test.net/api/', 
      SPHttpClient/HttpClient.configurations.v1,
      opt)
`
3) `let req = new XMLHttpRequest();
let uri = encodeURI('https://test.net/api/');
req.open('GET', uri)
req.setRequestHeader('Authorization', 'Bearer ' + accessToken);
req.onreadystatechange = function () {
	if (this.readyState === 4 /* compare */) {
		//Do something
	} 
};
req.send();`

**Option 3**: It works when I run it from console window outside the SharePoint page or workbench.html page
**Error: Authorization is missing in request headers**
![image](https://user-images.githubusercontent.com/26110193/27125195-b529e886-511d-11e7-9197-2c40ba0752bf.png)

Expected:
![image](https://user-images.githubusercontent.com/26110193/27125255-e550b0e4-511d-11e7-9a65-46ca953e4cb0.png)

**Comment by waldekmastykarz** [comment]
If I issue the call as follows, the Authorization header is sent along with the request:

```ts
// ...
import { HttpClient } from '@microsoft/sp-http';

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
  public render(): void {
      // ...
      this.context.httpClient.get('https://graph.microsoft.com/v1.0/me', HttpClient.configurations.v1, {
        headers: {
          'Authorization': 'Bearer abc'
        }
      });
  }
  // ...
}
```

**Comment by paulewert** [comment]
The call Waldek gives will work, but the linter considers it an error because the accepted type for the headers property in IHttpClientOptions--which extends RequestInit--is 'Headers | string[][]'. Thus, for the linter to accept the assigned value, you must do one of the following:
- `this.context.httpClient.get('https://graph.microsoft.com/v1.0/me', HttpClient.configurations.v1, { headers: [[ 'Authorization', 'Bearer abc']]);`
- `let h = new Headers();
h.append('Authorization', 'Bearer abc');
this.context.httpClient.get('https://graph.microsoft.com/v1.0/me', HttpClient.configurations.v1, h);`

**Comment by hugoabernier** [comment]
@honb did @waldekmastykarz and @paulewert 's answers help you resolve this issue?

I'll mark this issue as closed because it has been open since 2017. If you still need help with this, please don't hesitate to open a new one.
