### ISSUE TITLE
Update the SharePoint Framework Examples

### ISSUE THREAD

**Issue by lbranjord** [SharePoint/sp-dev-fx-webparts#266]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

As you know many of the examples are no longer able to be gulp serve because they have many errors in the log. They need to be updated so the group of individuals in the dev community may learn this technology. I am able to resolve some of these but not always.

**Comment by adamcoulombe** [comment]
+1.  I could not bundle the react-textboxio bundle.  Bunch of index.d.ts errors

![image](https://user-images.githubusercontent.com/469038/35743091-72fbae96-080a-11e8-8cc3-dd99ead09e52.png)

**Comment by VelinGeorgiev** [comment]
This is a community driven initiative. You can be part of it :1st_place_medal: . If you update a web part for yourself, you can create pull request to that repo with the updated code to keep the repo up to date. :+1:

**Comment by adamcoulombe** [comment]
I rebuilt this webpart using a fresh `yo @microsoft@sharepoint` scaffold. I did so by following the "recipe" [here](http://thecollaborationcorner.com/2017/10/29/an-alternative-to-the-sharepoint-default-rich-text-editor-in-modern-pages-textbox-io-with-spfx/) which was a great resource.

**Comment by hugoabernier** [comment]
@lbranjord  thanks again for bringing this to our attention. 

I'll close this issue, as the samples and the SPFx scaffolding has changed significantly since you opened the issue, but if you feel that there is still more work to do, please feel free to open another issue.

We also welcome your contributions! #SharingIsCaring!
