### ISSUE TITLE
React Content Query WebPart People Picker Filter [Me]-Token

### ISSUE THREAD

**Issue by schneika** [SharePoint/sp-dev-fx-webparts#342]
Is it possible to use the [Me]-Token as a Filter-Value in React Content Query WebPart.

#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Is there any other possibility to Filter on a People Column with the Current User,
like
Assigned to = [Me]

best regards

**Comment by spplante** [comment]
Hi @schneika,

I did include a "Me" checkbox that you can use instead of the people picker. When you chose a person field, there should be a people picker made available if you want to query against specific users, and but should also be a "Me" checkbox right under the people picker.

Let me know if that works out for you :)

**Comment by spplante** [comment]
@schneika, did this answer your question?

**Comment by schneika** [comment]
@spplante , thank you very much. The [Me]-Token already there ;-)

**Comment by spplante** [comment]
No problem!

@VesaJuvonen this can be closed :)

**Comment by spplante** [comment]
@schneika, could you close this issue please :)

Thanks!

**Comment by VesaJuvonen** [comment]
Closing - sorry for the small delay.

**Comment by spplante** [comment]
No problem, actually I just realized that the owner of an issue is allowed to close his own issue, so from now on I will ask the owner directly :+1:
