### ISSUE TITLE
react-real-time web part for on-premise?

### ISSUE THREAD

**Issue by cmd64** [SharePoint/sp-dev-fx-webparts#344]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
How can I use for on-premise with azure or without azure?

https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-real-time

**Comment by FranckyC** [comment]
Hi @cmd64. Yes I think you can, take a look at the on-premise connector for [Azure Logic Apps](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-gateway-connection). This is the only part you have to change if you already use SharePoint 2016 Feature Pack 2 including SPFx.

**Comment by FranckyC** [comment]
Hi @cmd64, maybe you can use a remote event receiver instead of Logic Apps to catch the item creation event and use [SignalR](https://www.asp.net/signalr) instead of Socket.io.

**Comment by hugoabernier** [comment]
Hi @cmd64 did @FranckyC 's suggestion ever get you further to resolving this issue? We'd love to hear how you solved it.

I'll go ahead and mark this issue as closed because there hasn't been any activity here for a while, but feel free to add more comments or open a new issue if you still need help.
