### ISSUE TITLE
Issue with React-Officegraph sample web part

### ISSUE THREAD

**Issue by dharmenb** [SharePoint/sp-dev-fx-webparts#358]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
React-Officegraph SPFx web part is not compiling with latest SPFx  tools
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-officegraph

#### Observed Behavior

There are many error like below:
Could not find implementations for the following rules specified in the configuration:
    prefer-const

Tried updating TSLint but no success.

#### Steps to Reproduce
1. Downloaded latest SPFx tools 
2. Download sample
3. Gulp Build -- gives the error

#### Submission Guidelines
_

**Comment by waldekmastykarz** [comment]
@dharmenb if I recall it correctly, the issue you mention is a warning not an error that's preventing the compilation, or has it changed? Have you tried running `gulp serve` to see if you can start the workbench and add the web parts?

**Comment by dharmenb** [comment]
Yeah I tried gulp serve, it is not working. Lot of other samples seems to broken as well.

Regards,
Dharmendra

Sent from my iPhone

On 12-Nov-2017, at 2:19 AM, Waldek Mastykarz <notifications@github.com<mailto:notifications@github.com>> wrote:


@dharmenb<https://github.com/dharmenb> if I recall it correctly, the issue you mention is a warning not an error that's preventing the compilation, or has it changed? Have you tried running gulp serve to see if you can start the workbench and add the web parts?

**Comment by StfBauer** [comment]
@waldekmastykarz I can confirm that it doesn't compile because the references in the package.json are outdated. This is the result of the update check:
![screen shot 2017-11-30 at 10 39 25](https://user-images.githubusercontent.com/5503835/33424197-58f0d192-d5bb-11e7-84c1-33bdda4f1e78.png)

After I upgraded all versions there were some deprecated warnings but overall it compiles and the web part can be found.
This are the problems I got:
![screen shot 2017-11-30 at 10 45 28](https://user-images.githubusercontent.com/5503835/33424272-9d1483c8-d5bb-11e7-8676-ba91fa2b2d78.png)

![screen shot 2017-11-30 at 10 45 51](https://user-images.githubusercontent.com/5503835/33424289-aa581612-d5bb-11e7-8616-d8ee1bd33ae1.png)

Node Version: v6.12.0
Npm Version: 5.5.1

**Comment by waldekmastykarz** [comment]
Thanks for confirming, @StfBauer. Regarding this particular sample, the question is if it would be worth upgrading, given that Office Graph is deprecated.

**Comment by StfBauer** [comment]
`git mv react-officegraph deprecated/react-officegraph` maybe ;)

**Comment by hugoabernier** [comment]
I updated the Readme file to indicate that the sample uses deprecated packages. If someone wants to create a newer version of this sample, please feel free to do so.
