### ISSUE TITLE
SharePoint Framework Textbox.io Rich Text Editor NOT FREE

### ISSUE THREAD

**Issue by mrsbeata** [SharePoint/sp-dev-fx-webparts#410]
So I got the webpart installed on SharePoint online and had an issue with it after a while. (Once a page with the webpart has been published it can't be edited) and I tried to get in Contact with them but they only nagged about me buying a license and not a thing towards fixing the issue - even though I was explicit that I could pay but I need them to work the issue first. Sort of testing their service ability.

But no. Only interested in getting paid. Please remove it from the repository since it is not free at all.

**Comment by AustinBreslinDev** [comment]
Textbook.io is built on top of tinymce, when Ephox bought tinymce they created textbook.io. TinyMCE is open source, if the dev who created this could switch to TinyMCE would that close this issue?

**Comment by andrewconnell** [comment]
What's wrong with it not being free and being in this repo? The sample was submitted by the community, not by the vendor.

This repo is just sample web parts and examples as the main [readme.md](https://github.com/SharePoint/sp-dev-fx-webparts) explains... it's not like Textbox.io is being distributed here...

**Comment by AustinBreslinDev** [comment]
Good point. These are only samples.
If I have time this week, I'll upload a TinyMCE version, it should be pretty much the exact same webpart.

**Comment by r12s** [comment]
Hi, I work at Ephox (maker of Textbox.io and TinyMCE). A few quick points for clarity:

1. Textbox.io is presently licensed under Creative Commons, and doesn't include free support. That's a commercial option and always has been.
2. Textbox.io is not built on top of TinyMCE. Textbox.io is a completely separate codebase. However, since the Ephox/TinyMCE merger back in 2015 there are now some shared libraries.
3. @mrsbeata if you're looking for a "free" editor with support, TinyMCE is definitely a better choice because you have access to [TinyMCE's community](https://community.tinymce.com/). As with Textbox.io, paid support is also available if you need guaranteed responses, SLAs, etc.

@AustinBreslinDev we'd love to see a TinyMCE integration. Let's chat.

I hope that provides some clarity.

**Comment by AustinBreslinDev** [comment]
Hi @r12s

Thanks for the clarification. I don't think I need help for this as of yet, but I will certainly reach out if needs be.

 I have already started on the TinyMCE integration. I have a branch for this on my fork.

Things I need to do on the branch.

1. Attach a chance event handler to the editor, to collect the rich text.
2. Pass this event up to the webpart.ts and store it in a queryable property of the webpart to make it work with the SharePoint Search.
3. Use DisplayMode of the Webpart to switch between edit and read.
4. Retrieve the property from the webpart properties and unescape the rich text so it displays correctly.

I plan to have these 4 items completed by Saturday evening GMT-0.

The TinyMCE APIs are rich enough that I know exactly how this needs to be built, it's the images part that I will have a problem with. There is a pull request currently in this repo documenting how to upload files, so I will need to read that to get file uploads to work.

I will create an update pull request for that some time next week.

I'll make sure to notify you when the first pull request is in.

**Comment by AustinBreslinDev** [comment]
Hi @mrsbeata,

Does this sample help with your issue? 
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-tinymce

If it does could you please click the close issue button, so others who have a similar issue can find a solution.

**Comment by brendon111** [comment]
I'm having trouble getting the React Textbox.io example to switch between edit and display mode. For me, it seems to always run in edit mode and strips out the images when I publish the page.

**Comment by FranckyC** [comment]
@mrsbeata Sorry for the late response, I've just seen this thread. As the author of this sample, I first apologize on this point. Maybe the licence terms were unclear and I've could mention this in the README file. Thanks @r12s for clarifications btw. I've assumed people will understand that Textbox.io is a 3rd party library made by a commercial company and any support of the library itself won't be a part of PnP. What I've provided here is just a way to integrate it within SPFx. At the time of my customer project, TinyMCE was not an option so we chose Textbox.io instead mainly because of the light UI and solid rich text editing capabilities. Being said, with current and surely future authoring improvements in SPO, maybe this WebPart won't be required anymore to achieve rich text editing scenarios.

**Comment by VesaJuvonen** [comment]
Unfortunately, Ephox submitted a DMCA Takedown request through GitHub and felt that having these community samples demonstrating their library usage is a violation of their license, even though the sample was following their Creative Commons CC BY-NC-ND 4.0 license guidance by providing proper credits and ensuring that the commercial use would require a different license.

It's a pity that we could not keep these community shared samples showing how to use textboxio in the context of SharePoint Online as the library as absolutely excellent. We have not followed up on Ephox's request to remove any samples with textboxio usage from this repository. 

Closing this one.

**Comment by FranckyC** [comment]
@VesaJuvonen Ok thank you for the update on this one. Do I have to remove these samples entirely?

**Comment by VesaJuvonen** [comment]
They are removed entirely now based on a request from Ephox.

**Comment by FranckyC** [comment]
Ok thanks @VesaJuvonen

**Comment by PooLP** [comment]
Hi,
I do not reopen this issue, but i have a little question. Why Microsoft not provide source or react lib of default rich text box used in SharePoint ?
Thanks,
PooLP

**Comment by FranckyC** [comment]
@PooLP The current editor used in modern pages is a customized version of the [CKEditor ](https://ckeditor.com/). I think exposing the source of the control would be too complicated since Microsoft has completety rewrited most of the capabilities if the original editor into the WP property pane. 

However, I agree it would be nice to have a way to reuse this control (not necessarily modify it) in our custom controls without using the full WP stack. For instance as a React component.

**Comment by PooLP** [comment]
Ideally it should be added in Office UI Fabric React component.
