### ISSUE TITLE
react-content-query-webpart fails to load Site Pages list when language is not English.

### ISSUE THREAD

**Issue by yogsodoth** [SharePoint/sp-dev-fx-webparts#426]
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
The react-content-query-webpart connects to the Site Pages list regardless of selected display language.

#### Observed Behavior
The react-content-query-webpart cannot connect to the Site Pages list when in a non-English language (tested in French). When "Pages du site" is selected as the target list with French as the active language in SharePoint, the webpart complains that the web URL is not valid on the second page where the Order By fields should be available for selection. The following error is shown: "An error occured while loading fields : The previously configured web url '/sites/<sitename>' is not found anymore. Either leave the WebPart properties as is or select another web url."
Theory: The web part is using the list title to get the list, rather than the GUID.

#### Steps to Reproduce
1) Add the app to tenant and deploy to a modern site collection (I'm using a Comms Site).
2) Place the web part on a page.
3) Switch your language preference for the site collection to French using https://<tenant>.sharepoint.com/sites/<sitename>/_layouts/15/regionalsetng.aspx?Type=user
4) Edit the web part
5) Select "/sites/sitename" as your site, "/" as your web, and "Pages du site" as your list. Go to the next settings page.
6) The dropdown for Order By should be blank and the error message should display.

**Comment by spplante** [comment]
Hi @yogsodoth, I will take a look at this shortly. I will be quite busy this week but I will try my best to fix this as soon as possible. Thanks!

**Comment by yogsodoth** [comment]
No worries, Simon-Pierre. I realize language in Modern pages/Comms sites is still not in a "production-ready" state anyway, so it's not just the web part that has issues. ;-)

**Comment by spplante** [comment]
Actually the issue that you found doesn't really have anything to do with the language, it's in fact a bigger problem: Whenever you configure the WebPart on a given list, if you change the list title in the future, the webpart won't display the results anymore since it's looking for the list using it's old title so it won't find it.

The same thing happens with the languages, if you configure the WebPart to look for the "Pages" library, and you access the site in french, there is no more "Pages" library so it doesn't find it.

I will simply edit the code so the list property stores the ID of the list instead of it's title and everything should be fine.

**Comment by spplante** [comment]
Hi @yogsodoth, I just submitted pull request #447 which will fix your issue. The WebPart now stores the selected list using its **Id** instead of its **Title**, which will fix the issue you had when accessing SharePoint in a different language. It will also fix the scenario where the selected list gets updated with a new title. 

If you don't want to wait for pull #447 to be merged to the dev branch before having the updated version, you can always access my [updated branch](https://github.com/spplante/sp-dev-fx-webparts/tree/dev).

Thanks again for finding this issue 👍 

@VesaJuvonen, this issue can be closed once PR #447 is merged :)

**Comment by aaronhawryluk** [comment]
Thanks @spplante! I'll wait for the merge!

**Comment by spplante** [comment]
@yogsodoth, can you close this issue please 👍 

Thanks!
