### ISSUE TITLE
SPFX Webpart release build not uploading in app catalog.

### ISSUE THREAD

**Issue by avinash-sah24** [SharePoint/sp-dev-fx-webparts#451]
#### Important

When I am trying to upload release build of a spfx webpart to app catalog. It is throwing an error Invalid SharePoint App package. Error: Part URI is not valid per rules defined in the Open Packaging Conventions specification."  

![image](https://user-images.githubusercontent.com/17885071/37384500-4f8bbaf2-2775-11e8-9dbe-b29714df03e8.png)

----
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Steps to Reproduce

1. create a sample webpart by running the Yeoman SharePoint Generator
2. build the solution
3. gulp bundle --ship
4. gulp package-solution --ship
5. upload the .sppkg file to app catalog.

**Comment by VesaJuvonen** [comment]
Hi @avinash-sah24 - as this is a generic issue and not related on any sample in this repository, please report the issue at http://aka.ms/spdev-issues, so that we get it tracked in our engineering efforts. Would also suggest sharing the solution (without modules folder) for understanding what has gone wrong. This exception is due issues in the json files.
