### ISSUE TITLE
React content query - pulling Sharepoint list data

### ISSUE THREAD

**Issue by spidersbite** [SharePoint/sp-dev-fx-webparts#457]
I'm using the react content query webpart. I'm trying to get a link into individual Sharepoint list records - the Title link. I do not know what to put in {{ }}. Is there guidance on this somewhere? 

#### Important

Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.

----

Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)[https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by spplante** [comment]
Since I replied to this question in another issue opened on my (personnal repository)[https://github.com/spplante/react-content-query/issues/8], here is the answer that I replied in case anyone is looking for the answer :

@spidersbite, I did a quick test and managed to make it work using the following code in the template :

```Handlebars
<a href="{{FileDirRef.textValue}}/DispForm.aspx?ID={{ID.textValue}}" target="_blank">{{Title.textValue}}</a>
```

Essentially, if you look up articles which explains how to link to the display form of an item, they explain that you must generate a link like the following :

**https://MyTenant.sharepoint.com/sites/MySite/MyList/DispForm.aspx?ID=4**

This is basically the URL or your list, followed by **/DispForm.aspx?ID=4** where **4** needs to be replaced by the ID of your item.

Fortunately, the WebPart gives you access to both informations using the following fields :

- Item's parent list url :  **FileDirRef**
- Item's ID : **ID**

Knowing this information, you can now select those two fields in the **ViewFields** property of the toolpane and build the links all by yourself 👍 

ProTip : I you want a good way to debug the information within each of your selected fields, just put the following markup at the beginning of your handlebars template :

```Handlebars
{{log items}}
```

This will basically log the **items** object directly in the console, so you can open the console and inspect in details all your items and their field values. This is an example of what it looks like in the console :

<img src="https://image.ibb.co/cJ9QqH/2018_03_22_15_27_36.png" alt="" />

Let me know if that helps ;)

**Comment by spplante** [comment]
@spidersbite  can you close this issue? 

Thanks!
