### ISSUE TITLE
sp-dialog error

### ISSUE THREAD

**Issue by sreejukg** [SharePoint/sp-dev-fx-webparts#474]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have a running tsx file that loads a ListView. The project loads fine. I ran the following command 
**npm install** **@ microsoft/sp-dialog**

Then in the tsx in added the following import statement. 
**import { SPHttpClient } from** '**@ microsoft/sp-http**';

When I use gulp build, I am getting the following error. 

**_Error - typescript - node_modules\@microsoft\sp-dialog\node_modules\@microsoft\sp-core-library\lib\deferredCl
ass\DeferredClass.d.ts(25,24): error TS1005: ';' expected._** 

I can see the error is pointing to the abstract keyword in the DeferredClass.ts file. How can I fix this?

**Comment by VesaJuvonen** [comment]
As this is generic SharePoint Framework issue rather than for related to any sample in this repository, we would ask this to get created to the sp-dev-docs issue list as noted in the issue template. This repository issue list should only contain issues around the samples. sp-dev-docs issue list is for documentation issues and also for any actual SPFx or SP Dev issues which could be potential issues with oob capabilities.
