### ISSUE TITLE
react-search-refiners should always use .module.scss instead of .scss

### ISSUE THREAD

**Issue by mcraiha** [SharePoint/sp-dev-fx-webparts#572]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@FranckyC  @VesaJuvonen 

## Expected or Desired Behavior

IMHO web parts should use identical structure for files. In react-search-refiners there are both  .module.scss (e.g. **TextDialog.module.scss**) and .scss (e.g. **SearchBoxWebPart.scss**) stylings used. The .scss way of life is a bit problematic since it causes gulp warnings which will cause issues for certain CI/CD pipelines because warnings == errors. 

## Steps to Reproduce

Use 
`gulp serve`
and notice warnings 

> [09:53:14] Warning - [sass] src\webparts\searchBox\SearchBoxWebPart.scss: filename should end with module.scss
[09:53:14] Warning - [sass] src\webparts\searchResults\components\SearchResultsWebPart.scss: filename should end with module.scss
  Request: [::1] '/workbench?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js'
[09:53:15] Warning - [sass] src\webparts\searchResults\components\Layouts\SearchResultsTemplate.scss: filename should end with module.scss

**Comment by FranckyC** [comment]
Hi @mcraiha. In theory, you're right but actually, due to the inner HTML structure used in components, it is not straightforward to use module.scss pattern because some classes are not generated properly. For **TextDialog.module.scss**, the control comes directly from the react-content-query SPFx sample with no modification.

To avoid issues with your CI, you can, in the case you use a PowerShell script, [redirect the error stream to the success stream](https://blogs.technet.microsoft.com/heyscriptingguy/2014/03/30/understanding-streams-redirection-and-write-host-in-powershell/) by using `gulp serve 2>&1` and check for errors by checking the $LASTEXITCODE value.
