### ISSUE TITLE
TaxonomyPicker: Cannot get context

### ISSUE THREAD

**Issue by pjwise** [SharePoint/sp-dev-fx-webparts#588]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@joelfmrodrigues 

## Expected or Desired Behavior

Taxonomy picker should work fine when on a page without the full path. See observed behavior below for a more detailed description. Might just need to add an option to pass the page context into the component to avoid this issue. 

## Observed Behavior

When on a home page the context query in the taxonomy picker fails.

e.g. a taxonomy picker on the following will fail: 
https://sometenant.sharepoint.com/sites/somesite

but it will not fail if I navigate to the full path: 
https://sometenant.sharepoint.com/sites/somesite/sitepages/home.aspx

## Steps to Reproduce

1) Navigate to a home page
2) Add a WebPart that has a taxonomy picker to the page
3) The taxonomy picker will error out
4) Navigate to the full path of that exact same page
5) The taxonomy picker works fine

**Comment by joelfmrodrigues** [comment]
@pjwise  what sample this refers to?
Have you also looked at the TaxonomyPicker from the PnP reusable controls?
https://sharepoint.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker/

**Comment by umaknow-jeanluc** [comment]
The problem is with the SP.ClientContext.get_current(), within the TaxonomyService.ts. MS library seems to remove the url past the last . in the href of the current page. When you're on the home page (without /sitepages/home.aspx), the context contains an invalid url, and it's passed along to create the taxonomy session.

To resolve that, change the spContext variable (getTermsById function in TaxonomyService) to create a new instance with your own url.

https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/src/services/TaxonomyService/TaxonomyService.ts : line 100

const spContext = new SP.ClientContext(this._context.pageContext.web.serverRelativeUrl);

**Comment by pjwise** [comment]
Thank you, we resolved this.
