### ISSUE TITLE
Writing tests for private functions

### ISSUE THREAD

**Issue by licypal** [SharePoint/sp-dev-fx-webparts#631]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

How do we write tests for private functions? Currently I make the function public and access the function via:

 let instance = reactComponent.instance() as <ComponenetName>;
 instance.<method>();

Please let me know how I can rewrite the test by keeping the method public. I'm using testing framework Jest, enzyme, sinon.

**Comment by VelinGeorgiev** [comment]
Because this is compiled to JavaScript you can always cast your object to any and access the method. Code should look something like:

```
let instance = reactComponent.instance();
(instance as any)["Your_private_function_name"]("Your_function_param1", "Your_function_param2");
```
I bit wierd, but it works. 
[Similar example can be found here](https://github.com/VelinGeorgiev/spfx-react-unit-testing/blob/a26b39a220ccd817b5b9938bee268eafafdd210d/src/webparts/iceCreamWebPart/test/part7PrivateMethod.test.tsx#L25). 
[And also here](https://github.com/pnp/office365-cli/blob/7f50b9a67d9c197e4dbf9cff68b7be2a03f7fa4d/src/o365/spo/commands/customaction/customaction-get.spec.ts#L726). 

The examples I pasted do not use Jest, but the technique is similar.

**Comment by licypal** [comment]
Thank you so much!

**Comment by VelinGeorgiev** [comment]
Always happy to help!
