### ISSUE TITLE
Is it possible to use office ui fabric components or css in react-content-query-webpart

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-fx-webparts#712]
I am actually trying to implement office ui fabric css , but it is not working.
How can i make it work ?
![image](https://user-images.githubusercontent.com/11780473/49521876-9ef64780-f8a6-11e8-9f6f-1ab666c092a9.png)

I can see the theme gets applied for a seconds and then changes to dark grey.

**Comment by harshdamaniahd** [comment]
I observed that , the css is overwritten
![image](https://user-images.githubusercontent.com/11780473/49522964-0f9e6380-f8a9-11e8-9eee-d1b4cbcd6ec4.png)

**Comment by nanddeepn** [comment]
Please see, if this helps you anyway:
[https://www.c-sharpcorner.com/article/sharepoint-framework-css-considerations/](https://www.c-sharpcorner.com/article/sharepoint-framework-css-considerations/)

**Comment by spplante** [comment]
@harshdamaniahd I didn’t add this functionnality so far in the WebPart. I know the Search Refiners webpart available in the samples recently added this exact possibility to use Office UI Fabric CSS in the templates, it could be a nice add on :)

Will let you know if I find aone time to add this functionality :)

**Comment by harshdamaniahd** [comment]
This is what I did,
I created a **common css** file  and packaged with the webpart.
for eg : 
![image](https://user-images.githubusercontent.com/11780473/50089191-60954c80-0205-11e9-9ff1-883796e15f8a.png)
Now, when I am using template or editing the template , I just have to use the **class** as highlighted below
![image](https://user-images.githubusercontent.com/11780473/50089245-8d496400-0205-11e9-9cf8-37e172c232ed.png)

Using this approach, I was able to make it aligned with Office UI Fabric Theme.
@spplante What do you think ?

**Comment by harshdamaniahd** [comment]
Great....Let me try :-)

**Comment by harshdamaniahd** [comment]
after including them, how can i use it in my template ?.. i tried but not working

**Comment by spplante** [comment]
@harshdamaniahd my bad, if you simply add the includes to **ContentQuery.module.scss** like I suggested, since it's a SASS **module**, the classes like **.cqwp** gets named at the compilation with a guid, which makes it impossible to use the classes in the Handlebars template because the template isn't aware of the GUID to use. So the way I initially suggested will create something like this :

```sass
.cqwp_3a5j23n56 {
    ...

    .ms-fontColor-themePrimary_3a5j23n56 {
        ...
    }
}
```

You can't do much with this you are right. To avoid this, use the **:global** selector in order to tell SASS that the incoming selector has to be excluded from the guid generation, and point directly to the global namesapce. That way the includes won't get the guid as well.

So the final solution is the following, in the **ContentQuery.module.scss** file :

```sass
.cqwp {
    :global .rootTemplate {
	@import '~office-ui-fabric/dist/sass/Fabric.scss';	
	@import '~office-ui-fabric/dist/components/Label/Label.scss';	
	@import '~office-ui-fabric/dist/components/List/List.scss';	
	@import '~office-ui-fabric/dist/components/ListItem/ListItem.scss'; 
        ...
    }
		
    .cqwpValidations {
        ...
    }
}
``` 

In your handlebars template :

```html
<div class="rootTemplate">
    <h1 class="ms-fontColor-themePrimary">Testing theme color!</h1>
</div>
```

Just tested it and it works 👍

**Comment by harshdamaniahd** [comment]
Thank you @spplante. Got it
