### ISSUE TITLE
DELETE this samples

### ISSUE THREAD

**Issue by gonadn** [SharePoint/sp-dev-fx-webparts#733]
Sorry to say, these samples never worked, and are the biggest SHITT code colected as a sample code here....!!

**Comment by StfBauer** [comment]
Your feedback requires some more details.

Which is the sample you have a problem to get it running?
Are there more than one sample you have an issue running it?
What exactly is the message, error, problem you get with this sample or these samples?

**Comment by VesaJuvonen** [comment]
thx @gonadn  - can you be slightly more specific on which samples would need to be adjusted? We also do welcome pull requests for these community contributed samples if you want to share anything. 

Many of the samples have been demonstrated in the community call as such, so they do work, which is why would love to get more details on the issues you are having. Thanks for the additional details advance, so that we can fix them for you and you can take advantage fo them.

**Comment by phillipharding** [comment]
@gonadn this repo is a community driven effort, no one gets paid to contribute to this, being polite at  least would be much more productive and likely to result in help with whatever problems you're having.
