### ISSUE TITLE
Dynamic Data - Connect Lost on Page Refresh, What Would Cause This?

### ISSUE THREAD

**Issue by Arknev** [SharePoint/sp-dev-fx-webparts#743]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

## Authors

@waldekm

## Expected or Desired Behavior

Custom extension would provide dynamic data to webpart and when set the connection would persist.

What I am trying to do is create an extension to provide some data to our future webparts in a solution we are preparing to build. The extension has to query the necessary data and fires notifyPropertyChanged when all values are set. The webpart in the linked repo is intended to be a sample for other devs on our team to build from.

## Observed Behavior

When the webpart is configured to connect to dynamic data from the custom extension, and all props are set, click apply, then the data values are correct and rendered as expected. When the page is published and I refresh, the connection to the extension is lost. The webpart will render as no connection exists and the config panel does not have "Remove Connection" link.

If I repeat this process and connect my webpart to "Page Environment > Site properties," setting all props to "Site link," apply, publish, refresh, then the webpart connection persists and renders the values. In this scenario, "Remove Connection" is available in the config panel.

## Steps to Reproduce

I am new to TS, React, and SPFx. I've been using template overrides, jQuery, JavaScript for years to build solutions for internal use. I'm stumped on this issue as there aren't any errors so I'm sure that I'm doing something to break the connection. 

I have put my code in a repo here: https://github.com/Arknev/ptAppGit
The custom extension src here: https://github.com/Arknev/ptAppGit/blob/master/ptAppMainExt2/src/extensions/ptAppMainExtension/PtAppMainExtensionApplicationCustomizer.ts

This repo is based on this article: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data

**Comment by FranckyC** [comment]
Hi @Arknev I had the same issue in the previous version of the react-search-refiners WebPart. The issue is because the source id for an extension dynamic data source changes every time you refresh the page because it is based on the instance id property so that's why other WP can't see it anymore.

To resolve this, in your consumer WPs, you have basically to persist the connection information when saving the property pane configuration (in the WP property bag) and "reconnect" it manually afterwards based on the builtin _registerAvailableSourcesChanged_ dynamic data provider method. You will have to compare the source component ids (which never changes compared to _instanceId_) every time a new source is available on the page (stored _componentId_ vs new source _componentId_).

I did this in a previous version of this sample but the code is not used anymore and uses SPFx < 1.7.0 so it may not work property for newer versions but it can give you at least an hint on how do achieve this:

The helper class to find a source by name or component id id: [here](https://github.com/SharePoint/sp-dev-fx-webparts/blob/fbb928831df3b38c6f44e64b133b8c72515b407a/samples/react-search-refiners/src/helpers/DynamicDataHelper.ts).
The interface to store a connection: [here](https://github.com/SharePoint/sp-dev-fx-webparts/blob/fbb928831df3b38c6f44e64b133b8c72515b407a/samples/react-search-refiners/src/models/IDynamicDataSourceConnection.ts).
An example of a consumer WP that uses all a this. See the **_reconnectDataSource** method called from the **onInit** method). This method calls the **registerAvailableSourcesChanged** which triggers the render every time a new source is available on the page: [here](https://github.com/SharePoint/sp-dev-fx-webparts/blob/910d377a77a508c58c934b8ae4ac2aaa79c8a12e/samples/react-search-refiners/src/webparts/searchResults/SearchResultsWebPart.ts).

**Comment by Arknev** [comment]
@FranckyC  Thanks for the information and I understand the issue clearly now. At this stage I'm trying to prove that functionality we have used in Classic can be duplicated in Modern. It sounds like there may not be an OTB method to reconnect to the extension. My concern here is "the code is not use anymore" and "may not work for newer versions." I can wait for this limitation to be addressed in a future version if that is in progress. Perhaps someone out there can share with us the intended method to connect an Extension to a WebPart.

**Comment by FranckyC** [comment]
@Arknev when I say "may not work for newer versions" I mean the Dynamic Data feature implementation changed slightly since the 1.7.0 version and would need some adaptation but it is totally feasible. I gave you all the building blocks you need to implement it ;)

**Comment by Arknev** [comment]
@FranckyC I appreciate the help and direction but I'm having trouble extracting the necessary code. I keep bringing in the code I find which leads to something else, then something else. The more I look at the code it seems to me this is something that the WebPart should handle. I can't imagine that the code wouldn't be able to detect if a connection is coming from an Extension or other WebPart and adjust accordingly. Furthermore, I don't want to write and build on code that might end up being replaced by OTB functionality.

I think I see what you mean by the code being removed because when I pull the sample down with Git, all of the dynamic data functionality is not included which makes it impossible to examine the code as I would normally in VS Code. Maybe I'm doing something wrong there but I can't find it in the repo when I pull down.

I hope we can get a sample or guidance on how to use an Extensions as dynamic data provider at the same level as the sample I referenced in my post above.

Thank you.
