### ISSUE TITLE
React Content Query WebPart - filter on calculated field

### ISSUE THREAD

**Issue by aosgodske** [SharePoint/sp-dev-fx-webparts#758]
I have installed this app in Sharepoint 365. And it is running, and it looks great.
But I need to filtrer on calculated fields. If I do that - the result is empty.

No matter what I do, and what calculated field i try on. It ends out empty. 

No problem in filtering on other normal fields

**Comment by spplante** [comment]
Hi @aosgodske,

Sorry for the delay I just this issue. I did some testing on my side and I am able to filter on a calculated column without a problem :

![Screenshot](https://i.ibb.co/Jzd6t2g/Proof.png)

Can you describe what's the exact value you are trying to filter? Give some more details I will try to see on my side.

Thanks!

**Comment by aosgodske** [comment]
I have tested again, it is only on fileds with dates and numbers in. It is both calculated fileds stored a dates, numbers and single line of text. Fx: value, 1 ,2 ,3 ,4 ,5 and I want to show all with 5 as value. Both Equals and does not equals to 5 ends out empty

**Comment by spplante** [comment]
Ok I found the issue. The problem is that the CAML query behind the scene is always generated as following for a calculated field :

```xml
<Query><Where><Eq><FieldRef Name="MyCalculatedField" /><Value Type="Text">5</Value></Eq></Where></Query>
```

No matter what you type in the filter's value field, the CAML query gets generated with <Value **Type="Text"**> and based on the research I just did, when querying calculated field, the value type must match the field value type, which isn't always text. 

The code would basically have to evaluate what you are typing in the filter's field value and specify the correct type based on it, but again it's a tricky one because how do I know if you are looking for **5** or **"5"** :|

I will try to update the code when I can but for now you can use the following workaround :

If it doesn't make a difference for you, just make sure your calculated field returns a string in order to make it filterable by the CQWP. For example, I changed the formula from :

```
=[MyNumberField]
```

to 

```
=UPPER([MyNumberField])
```

And everything works perfectly now that my calculated field returns a string. You can use the **Text()** function for date fields to return a string as well.

Let me know if that helps.

👍

**Comment by aosgodske** [comment]
Right now im using a workaround. Im sorting on a date column and only showing a few elements. 
So I will wait until you have changed the codes. 
In this case I need to filter with today() in a calculated field stored as date
