### ISSUE TITLE
Webpart losing properties on refresh

### ISSUE THREAD

**Issue by unyon** [SharePoint/sp-dev-fx-webparts#870]
I am using the react-calendar webpart.  I configure the webpart to an existing calendar which works.  When I refresh the page it loses these properties and shows an error that it cannot find the list.  How can I fix it so it saves the properties after I connect it to a list.  

This is the error:
`Error making HttpClient request in queryable [404] Not Found ::> {"odata.error":{"code":"-2130575322, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"List does not exist.\n\nThe page you selected contains a list that does not exist. It may have been deleted by another user."}}}`

- [x] Question
- [ ] Bug
- [ ] Enhancement

**Comment by viper4531** [comment]
I am also getting this issue with the react-calendar webpart.  
![image](https://user-images.githubusercontent.com/50877521/58105348-5ad8d400-7bb4-11e9-9fb2-67fd0a2a59e3.png)

**Comment by hugoabernier** [comment]
@unyon did you get a resolution to this issue?

The react-calendar web part was updated since you submitted this issue. If you're still experiencing the issue with the newer web part, please feel free to re-submit this as a new issue and we'll see if we can get more community members to look into it.
