### ISSUE TITLE
React calendar is not working in internet explorer 11 and in edge

### ISSUE THREAD

**Issue by shobhitbhalla1** [SharePoint/sp-dev-fx-webparts#881]
Component link  : sp-dev-fx-webparts/samples/react-calendar/

React calendar is not rendering in edge and internet explorer

**Comment by schneika** [comment]
The object does not render the Property or method "from" in IE11

**Comment by joelfmrodrigues** [comment]
This error is down to a missing IE11 polyfil for PnPjs.
https://pnp.github.io/pnpjs/documentation/polyfill/ 
But even after solving this error, I'm getting a different one

**Comment by gauti786** [comment]
After adding the polyfills for IE11, we need to install polyfills to support ES5 and lower versions.
Array.prototype.find ES6 polyfill for ES5 versions and lower via NPM, you only need to require the module in order to have it working in order to use knowing that is going to work in browsers that does not support this function natively.

https://github.com/jsPolyfill/Array.prototype.find



> 
> 
> This error is down to a missing IE11 polyfil for PnPjs.
> https://pnp.github.io/pnpjs/documentation/polyfill/
> But even after solving this error, I'm getting a different one

**Comment by hugoabernier** [comment]
@shobhitbhalla1  did @gauti786's solution solve the issue?
