### ISSUE TITLE
react-content-query-webpart For Documents

### ISSUE THREAD

**Issue by dheepai** [SharePoint/sp-dev-fx-webparts#923]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

## Observed Behavior
The DocIcon and the ServerREdirectedUrl fields are not being returned for the documents in a Document library. Is there a way to display those?

**Comment by spplante** [comment]
Hi @dheepai , **DocIcon** and **ServerRedirectedUrl** are not list item fields, they are managed properties returned from search results. The content query webpart does not use search behind the scenes, it uses a CAML query in order to return the items matching its query along with their field values (the one you selected).

You can build the icon and server redirected url yourself using some logic in the handlebars template or a simple **helper** that could return you the icon based on the **File_x0020_Type** field value, then the helper could be used in your template with something like this :

{{getDocumentIcon File_x0020_Type}}

Otherwise you can use the **Search Refiners** WebPart which uses the search instead of a CAML query.

**Comment by hugoabernier** [comment]
@dheepai I hope @spplante 's answer was what you were looking for?

I'll go ahead and close this issue because there hasn't been any activity on it, but feel free to re-open it if you need more help with this.
