### ISSUE TITLE
Looking for best practices for loading data

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-fx-webparts#970]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Expected or Desired Behavior

I'm hoping to initiate a conversation regarding SharePoint Web Part development best practices, particularly as it relates to how/when to load data.

I would like to hear from other members of the community and SPFx gurus what you think the best approach is.

Particularly, I'd like your views on:
- Where should the data be loaded (WebPart or sub-component)
- The use of state (or not)
- Patterns for performance

If possible, I would like to keep this discussion to a standard pattern which is easily applied for newcomers as well as experts. (In other words, I would prefer avoiding the use of Redux or Mobx as the go-to approach)

## Observed Behavior

Looking at the samples in this repo and out there on the web, I have observed two approaches:
- The data is loaded within the `WebPart` object and passed to its sub-components. The sub-component displays the data; or
- The web part's component loads and displays the data.

I have also noticed that many newcomers have a tendency to delay the rendering of the web part until the data is loaded, vs displaying a "loading" message, a spinner, or a shimmer.

I understand that every design will have its own merit, but I'm looking to see if the PnP community has a common pattern they like to use.

I have my own go-to approach, but my goal here isn't to influence the conversation.

If this isn't the right venue for this type of conversation, I apologize in advance!

**Comment by russgove** [comment]
Hi Hugo, i'm no guru, but in general if my react component is,just going to display the data, i retrieve it in the spfx component and pass it as props to react.  If the exact component is going to update the data, i generally fetch it in the react component and store it in state. 

In early projects i tried making the spfx component responsible,for all data i/o . This got messy because i needed to pass a bunch of callback methods to the react component. it didn't really add any value,  other than perhaps,imcould more easily test the react component.

So for static data , i usually pass it as props. dynamic data, if do it all in react,

In earlier versions of react/spfx there was a way ( a hack) to re-render the react component with new values for the props. The hack i used to use is no longer works.

What is your general practice?
